#!/bin/sh

# simple X hotkey daemon
sxhkd &
# display wallpaper by feh
feh --randomize --bg-fill ~/Pictures/Wallpapers
# change cursor style
xsetroot -cursor_name left_ptr &
# launch polybar
$HOME/.config/polybar/launch.sh
# fcitx input-method
fcitx &


pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor eDP-1 -d I II III IV V
bspc monitor HDMI-1 -d VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           12

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color "#ee00ff"
bspc config active_border_color "#38369c"
bspc config focused_border_color "#00ffff"
bspc config presel_feedback_color "$color1"
bspc config focus_follows_pointer true
bspc config bottom_padding 5
bspc config top_padding 30
bspc config left_padding 5
bspc config right_padding 5

#bspc rule -a firefox desktop='^2' state=tiled follow=off
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
